name: Create Gerber Files

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo add-apt-repository --yes ppa:kicad/kicad-5.1-releases
        sudo apt-get update
        sudo apt-get install --yes kicad kicad-libraries kicad-symbols kicad-templates kicad-footprints kicad-packages3d
    - name: Create gerber files
      run: make
    - uses: actions/upload-artifact@v1
      with:
        name: rflego_gerber.zip
        path: gerber/
